/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VerificationOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decodeCredentialsResponse"
      | "decodeResponse"
      | "getVerificationStatus"
      | "handleOracleFulfillment"
      | "owner"
      | "renounceOwnership"
      | "requestVerification"
      | "transferOwnership"
      | "updateConfig"
      | "userVerifications"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RequestFailed"
      | "VerificationCompleted"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "decodeCredentialsResponse",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeResponse",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleOracleFulfillment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userVerifications",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeCredentialsResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleOracleFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVerifications",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFailedEvent {
  export type InputTuple = [requestId: BytesLike, reason: BytesLike];
  export type OutputTuple = [requestId: string, reason: string];
  export interface OutputObject {
    requestId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationCompletedEvent {
  export type InputTuple = [
    user: AddressLike,
    kycPassed: boolean,
    amlPassed: boolean,
    credentialHash: string,
    verificationSource: string
  ];
  export type OutputTuple = [
    user: string,
    kycPassed: boolean,
    amlPassed: boolean,
    credentialHash: string,
    verificationSource: string
  ];
  export interface OutputObject {
    user: string;
    kycPassed: boolean;
    amlPassed: boolean;
    credentialHash: string;
    verificationSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [requestId: BytesLike, user: AddressLike];
  export type OutputTuple = [requestId: string, user: string];
  export interface OutputObject {
    requestId: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerificationOracle extends BaseContract {
  connect(runner?: ContractRunner | null): VerificationOracle;
  waitForDeployment(): Promise<this>;

  interface: VerificationOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decodeCredentialsResponse: TypedContractMethod<
    [response: BytesLike],
    [[string, string]],
    "view"
  >;

  decodeResponse: TypedContractMethod<[response: BytesLike], [boolean], "view">;

  getVerificationStatus: TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, boolean, string, string, bigint, boolean] & {
        kycPassed: boolean;
        amlPassed: boolean;
        credentialHash: string;
        verificationSource: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;

  handleOracleFulfillment: TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestVerification: TypedContractMethod<
    [user: AddressLike, documentHash: string],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateConfig: TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      donId: BytesLike,
      gasLimit: BigNumberish,
      kycSource: BytesLike,
      amlSource: BytesLike,
      credentialsSource: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  userVerifications: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, string, bigint, boolean, string] & {
        kycPassed: boolean;
        amlPassed: boolean;
        credentialHash: string;
        verificationSource: string;
        timestamp: bigint;
        isValid: boolean;
        lastRequestId: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decodeCredentialsResponse"
  ): TypedContractMethod<[response: BytesLike], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "decodeResponse"
  ): TypedContractMethod<[response: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getVerificationStatus"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [boolean, boolean, string, string, bigint, boolean] & {
        kycPassed: boolean;
        amlPassed: boolean;
        credentialHash: string;
        verificationSource: string;
        timestamp: bigint;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "handleOracleFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<
    [user: AddressLike, documentHash: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<
    [
      subscriptionId: BigNumberish,
      donId: BytesLike,
      gasLimit: BigNumberish,
      kycSource: BytesLike,
      amlSource: BytesLike,
      credentialsSource: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userVerifications"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, string, bigint, boolean, string] & {
        kycPassed: boolean;
        amlPassed: boolean;
        credentialHash: string;
        verificationSource: string;
        timestamp: bigint;
        isValid: boolean;
        lastRequestId: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestFailed"
  ): TypedContractEvent<
    RequestFailedEvent.InputTuple,
    RequestFailedEvent.OutputTuple,
    RequestFailedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationCompleted"
  ): TypedContractEvent<
    VerificationCompletedEvent.InputTuple,
    VerificationCompletedEvent.OutputTuple,
    VerificationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestFailed(bytes32,bytes)": TypedContractEvent<
      RequestFailedEvent.InputTuple,
      RequestFailedEvent.OutputTuple,
      RequestFailedEvent.OutputObject
    >;
    RequestFailed: TypedContractEvent<
      RequestFailedEvent.InputTuple,
      RequestFailedEvent.OutputTuple,
      RequestFailedEvent.OutputObject
    >;

    "VerificationCompleted(address,bool,bool,string,string)": TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;
    VerificationCompleted: TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;

    "VerificationRequested(bytes32,address)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
