/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILinkTokenInterface__factory } from "./ILinkTokenInterface__factory";
export { MockOracle__factory } from "./MockOracle__factory";
