/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockOracleSol from "./MockOracle.sol";
export type { mockOracleSol };
export type { MockERC20 } from "./MockERC20";
export type { MockFunctionsRouter } from "./MockFunctionsRouter";
export type { MockLinkToken } from "./MockLinkToken";
export type { MockV3Aggregator } from "./MockV3Aggregator";
