/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILinkTokenInterface } from "./ILinkTokenInterface";
export type { MockOracle } from "./MockOracle";
